[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.1"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  # The version rule is used for a specific release and the master branch for in between releases.
  # branch = "master"
  version = "=v0.0.6"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "v1.13.3"