---
SSO_DISABLE_SSL_CERTIFICATE_VALIDATION: FALSE
SSO_OPENIDCONNECT_DEPLOYMENTS: ROOT.war
KIE_ADMIN_PWD: RedHat
KIE_SERVER_CONTROLLER_PWD: RedHat
KIE_SERVER_PWD: RedHat
KIE_SERVER_USER: executionUser
KIE_MBEANS: enabled
KIE_SERVER_CONTROLLER_USER: controllerUser
KIE_ADMIN_USER: adminUser
